sudo: required
services:
  - docker

before_install:
  - docker build -t smithpeder/docker-travis-test -f Dockerfile.dev .

script:
  - docker run smithpeder/docker-travis-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-travis-test"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-119369441851"
  bucket_path: "docker-travis-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"