sudo: required
services:
  - docker

before_install:
  - docker build -t smithpeder/docker-travis-test -f Dockerfile.dev .

script:
  - docker run smithpeder/docker-travis-test npm run test -- --coverage